apiVersion: apps/v1
kind: Deployment
metadata:
  name: asa_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asa_backend
  template:
    metadata:
      labels:
        app: asa_backend
    spec:
      containers:
        - name: asa_backend
          image: asa_backend:latest
          ports:
            - containerPort: 3010