# rails-app-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rails-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asa-backend
                port:
                  number: 80
