---
openapi: 3.0.1
info:
  title: ASA Backend API
  version: v1
paths:
  "/api/advances":
    get:
      summary: Retrieves all advances
      tags:
      - Advances
      parameters:
      - name: advance
        in: query
        schema:
          type: object
          properties:
            status:
              type: array
              items:
                type: string
            advance_type:
              type: array
              items:
                type: string
            type:
              type: string
          required:
          - status
          - advance_type
      responses:
        '200':
          description: advances found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    advance_type:
                      type: string
                    status:
                      type: string
                    amount:
                      type: number
                    verified_by:
                      type: integer
                      nullable: true
                    confirmed_by:
                      type: integer
                      nullable: true
                    dispatch_by:
                      type: integer
                      nullable: true
                    user_id:
                      type: integer
                    created_at:
                      type: string
                      format: date_time
                    updated_at:
                      type: string
                      format: date_time
                  required:
                  - id
                  - advance_type
                  - status
                  - amount
                  - user_id
                  - created_at
                  - updated_at
        '404':
          description: advances not found
    post:
      summary: Creates an advance
      tags:
      - Advances
      parameters: []
      responses:
        '201':
          description: advance created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                advance_type:
                  type: string
                status:
                  type: string
                amount:
                  type: number
              required:
              - advance_type
              - status
              - amount
  "/api/advances/{id}":
    get:
      summary: Retrieves an advance
      tags:
      - Advances
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: advance found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  advance_type:
                    type: string
                  status:
                    type: string
                  amount:
                    type: number
                  verified_by:
                    type: integer
                    nullable: true
                  confirmed_by:
                    type: integer
                    nullable: true
                  dispatch_by:
                    type: integer
                    nullable: true
                  user_id:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - advance_type
                - status
                - amount
                - user_id
                - created_at
                - updated_at
        '404':
          description: advance not found
  "/api/rates":
    get:
      summary: Retrieves a specific rate
      tags:
      - Rates
      parameters:
      - name: rate
        in: query
        schema:
          type: object
          properties:
            from:
              type: string
            to:
              type: string
          required:
          - from
          - to
      responses:
        '200':
          description: rate found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  from:
                    type: string
                  to:
                    type: string
                  grade_id:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - from
                - to
                - grade_id
                - created_at
                - updated_at
        '404':
          description: rate not found
    post:
      summary: Creates a rate
      tags:
      - Rates
      parameters: []
      responses:
        '201':
          description: rate created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                grade_id:
                  type: string
              required:
              - from
              - to
              - grade_id
  "/api/rates/countries":
    get:
      summary: Retrieves all countries with rates
      tags:
      - Rates
      responses:
        '200':
          description: countries found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  users/sign_in:
    post:
      summary: Sign in user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user signed in
        '401':
          description: unauthorized user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
              - login
              - password
  users/sign_out:
    delete:
      summary: Sign out user
      tags:
      - Authentication
      responses:
        '200':
          description: user signed out
servers:
- url: https://127.0.0.1:3000
  variables:
    defaultHost:
      default: www.example.com
