default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: 3306
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
#  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: asa_backend_development

test:
  <<: *default
  database: asa_backend_test

production:
  <<: *default
  database: asa_backend_production
  host: <%= ENV["DATABASE_HOST"] %>
